Use dall-e instead of bing image search
preparingforexams/hhh-diff-bot pull request #102
Opened 2023-03-07 13:03 UTC by torbencarstens

2023-03-07 18:31 UTC, BjoernPetersen requested changes

2023-03-07 18:31 UTC, BjoernPetersen commented on telegram_bot/openai.py
> +    return response.content
Waiiiiit a second, I've seen this before!

2023-03-07 18:31 UTC, BjoernPetersen commented on telegram_bot/openai.py
> +    return response.content
I suggest you apply this patch as well: https://github.com/preparingforexams/telegram-horoscope-bot/commit/f70aae100f917f0e97c78aac454464918de82dcc

2023-03-07 18:31 UTC, BjoernPetersen commented on telegram_bot/openai.py
> +        size="512x512",
BTW: there are options for 1024x1024 and 256x256. We _could_ use 256 since it's only a chat photo (which is usually viewed in basically thumbnail size). On the other hand, if the result is actually good, we'll want to have the opportunity to inspect it in detail, I guess.

2023-03-07 18:35 UTC, BjoernPetersen commented on telegram_bot/openai.py
> +    return response.content
FYI, this is the error response I got:

```
{
  error: {
    code: None, 
    message: 'Your request was rejected as a result of our safety system. Your prompt may contain text that is not allowed by our safety system.',
    param: None, 
    type: 'invalid_request_error'
  }
}
```

2023-03-07 18:36 UTC, BjoernPetersen commented on telegram_bot/openai.py
> +    return response.content
See also https://bjoern-petersen.sentry.io/share/issue/7dd76ab89ede423fb6033a4bc188ef1b/

2023-03-07 21:42 UTC, torbencarstens commented on telegram_bot/openai.py
> +        size="512x512",
I prefer a slightly larger size for this since I'll definitely look closer at the generated images

2023-03-08 11:06 UTC, torbencarstens commented
I'll rework the permission check to be slightly more accurate

2023-03-08 11:18 UTC, BjoernPetersen approved these changes

2023-03-08 17:50 UTC, merged