Add invite link to chat_title (html) if present
preparingforexams/hhh-diff-bot pull request #32
Opened 2021-01-23 00:19 UTC by torbencarstens

2021-01-23 00:21 UTC, torbencarstens commented
Check that we're not exceeding the max message size with this anytime soon

2021-01-23 00:31 UTC, torbencarstens commented
We're way too close to the limit... `Text of the message to be sent, 1-4096 characters after entities parsing`, without entity parsing we're at 4099 characters/message (roughly 4k with)...

#15 NEEDS to happen before this.

2021-11-17 16:30 UTC, BjoernPetersen requested changes

2021-11-17 16:30 UTC, BjoernPetersen commented on telegram_bot/bot.py
> +                if chat and chat.invite_link:
Why `if chat`?

2021-11-17 16:35 UTC, torbencarstens commented on telegram_bot/bot.py
> +                if chat and chat.invite_link:
Updated in 93ea0cc, was just an automatic insertion from my side to validate that chat is not none, this is done before calling `chat_to_item` already though.

The type hint would've been wrong otherwise.

2021-11-17 16:37 UTC, BjoernPetersen approved these changes

2021-11-17 16:37 UTC, merged