Split text into multiple messages
preparingforexams/hhh-diff-bot pull request #33
Opened 2021-01-23 12:18 UTC by torbencarstens

kicked from chat (reduced message count)
-> delete old unused messages

added to chat (increased message count)
-> send a new set of message

Closes #15

2021-01-23 14:30 UTC, torbencarstens commented
Migrate all internal ids to int.

2021-01-23 15:43 UTC, BjoernPetersen requested changes

2021-01-23 15:43 UTC, BjoernPetersen commented on telegram_bot/bot.py
> +        :arg prefix: Will throw off the `deductable_per_chat` by `deductable_per_chat`.
* Should use `:param`
* The description doesn't make much sense to me

2021-01-23 15:43 UTC, BjoernPetersen commented on telegram_bot/bot.py
> +        deductable_per_chat = 0
This variable is never written to

2021-01-23 16:00 UTC, torbencarstens commented on telegram_bot/bot.py
> +        deductable_per_chat = 0
`We need this for the invite links` (https://github.com/torbencarstens/hhh-diff-bot/issues/15#issuecomment-765799796)

2021-01-23 16:04 UTC, torbencarstens commented on telegram_bot/bot.py
> +        :arg prefix: Will throw off the `deductable_per_chat` by `deductable_per_chat`.
The comment is wronng anyway, I initially wanted to calculate the length different than I do now. It doesn't affect anything anymore.

2021-01-23 16:05 UTC, BjoernPetersen approved these changes

2021-11-17 13:06 UTC, torbencarstens commented
I've the feeling that there was a bug in this implementation, needs testing before a merge can happen.

2021-11-17 16:03 UTC, merged